version: '3.8'

services:
  adot:
    build:
      context: ./adot
    ports:
      - "4318:4318"
    networks:
      - adot-network

  app:
    build:
      context: ./app2
    ports:
      - "8080:8080"
    networks:
      - adot-network

networks:
  adot-network:
    driver: bridge
